services:
  postgres:
    image: postgres:16-alpine
    container_name: ytz_postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: local_dev
      POSTGRES_PASSWORD: local_dev_password
      POSTGRES_DB: ytz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U unbiased" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
